package com.grpcdemo.crudop.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.boot.autoconfigure.domain.EntityScan;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="userinfo")
public class User {

        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        String id;

        @DynamoDBAttribute
        private String userName;

        @DynamoDBAttribute
        private String userPhoneNumber;

        @DynamoDBAttribute
        private String userBalance;

}

